---
title: "lego"
output: html_document
---

```{r setup, include = FALSE, error = FALSE}
knitr::opts_chunk$set(echo = FALSE, error=F, warning=F)
library(tidyverse) # CSV file I/O, e.g. the read_csv function
library(RColorBrewer)
library(plotly) #contain hex to RGB conversion
#date
library(lubridate)
#machinelearning
library(caret)
#text
library(tidytext)
library(spacyr)
#theme
my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text = element_text(face="bold"),
    plot.background = element_rect(fill = 'snow2',color='white'),
    strip.text.y = element_text(angle=180),
    legend.position = 'None', legend.title = element_blank())
}

```

## Load data

```{r input}
setwd("/Users/hannah/git_repo/opendata_viz/lego")
inventories <- read_csv("inventories.csv")
inventory_parts <- read_csv("inventory_parts.csv")
inventory_sets <- read_csv("inventory_sets.csv")
sets <- read_csv("sets.csv")
parts <- read_csv("parts.csv")
themes <- read_csv("themes.csv")
part_categories <- read_csv("part_categories.csv")
```



```{r pre_process}
colors <- read_csv("colors.csv")
#convert hex to rgb
colors <- colors %>% 
  mutate(hex = paste0("#", rgb),
         alpha = ifelse(is_trans == 't', 0.8, 0),
         rgb = toRGB(hex)) %>%
  separate(rgb, into=c('prefix','r','g','b','alp'), sep = "\\(|,|\\)") %>%
  mutate(rgb = paste(r, g, b, sep=',')
         #hsv = rgb2hsv(rgb)
         )
```

## main color
scatter with lines chart (simple yet fun)


## sort color
convert rgb to hsv space
```{r}
colors_rgb <- colors %>%
  select(r,g,b) %>% mutate_all(as.numeric)
colors_hsv <- t(rgb2hsv(t(colors_rgb))) %>% as.data.frame()
colors <- colors %>% cbind(colors_hsv)
```

```{r merge}
merge <- sets %>% 
  left_join(inventories, by = "set_num") %>%
  left_join(inventory_parts, by = c("id" = "inventory_id")) %>%
  left_join(colors, by = c("color_id" = "id")) 
```

```{r}
brick_colors = merge %>%
  mutate(decade = year- (year%%10)) %>%
  group_by(hex, h, decade) %>%
  dplyr::summarize(total = n())
  
```

## unique colors
```{r distinctcolor}
pal <- unique(colors$hex)
names(pal) <- unique(pal) 


brick_colors %>%
          ggplot( aes(x = reorder(hex, h), y=1, fill = hex)) + 
          geom_col() + 
                 
          ggtitle("7 Decades of Lego brick colors") +
          scale_fill_manual(values = pal)+ 
          facet_grid(decade~., switch="both") + 
          theme_void( ) +
          my_theme() + theme(axis.text.y=element_blank(),
                             axis.text.x=element_blank()) +
  labs(caption = "source: Rebrickable")  

```


```{r distinctcolor}
pal <- unique(colors$hex)
names(pal) <- unique(pal) 

brick_colors_yr = merge %>%
  group_by(hex, h, year) %>%
  dplyr::summarize(total = n())

brick_colors_yr %>%
          ggplot(aes(x = year, y=1, fill = reorder(hex, h))) + 
          geom_col(color = 'white', size=0.01) + 
          labs(caption = "source: Rebrickable")  +    
          scale_x_continuous(breaks = seq(1950,2020, by=10)) + 
          scale_y_continuous(breaks = seq(0,120, by=20)) + 
          ggtitle("Distinct Colors of Lego brick 1950 - 2017") +
          scale_fill_manual(values = pal) +
          theme_void( ) +
          my_theme() + theme(plot.margin=unit(c(1,1,1.5,1.2),"cm"))

```

```{r}
brick_colors_yr %>% group_by(year) %>%
  dplyr::summarize(n_col = n_distinct(hex)) %>%
  arrange(-n_col) %>% head()
```

## color mix among top sets with most pieces

```{r}
top20set <- sets %>% top_n(20, num_parts)
topsetcolor <- top20set %>% 
  inner_join(brick_color, by = c("name" = "name.x"))
d=top10setcolor%>%filter(name=='The Disney Castle') 
 table(d$year.x)
```

```{r}
png('legoset.png')
topsetcolor %>% group_by(name, hex, h) %>%
  dplyr::summarize(n = sum(num_parts.x)) %>%
  ggplot(aes(1, n, fill=reorder(hex,h))) + 
  geom_bar(stat='identity', position = 'fill') +
          scale_fill_manual(values = pal) +
  labs(title ='Color Mix of Lego Sets with Most Pieces', caption = "source: Rebrickable") +
  coord_flip() +
  facet_grid(name~., scales='free', switch="both") +
  theme_void( ) + 
  theme(axis.text.y=element_blank(),
        axis.text.x=element_blank(),
        strip.text.y=element_text(hjust=1),
        plot.margin=unit(c(1,0,0.5,0),"cm"),
        plot.title = element_text(hjust = -0.5)
        ) + theme() +
  my_theme() 
dev.off()
```


## color mix among top themes with most sets


```{r}
df_themes <- themes %>% 
  left_join(merge, by =c("id" = "theme_id"))
```

```{r}
top20theme <- df_themes %>% 
  group_by(name) %>%
  summarize(n = n_distinct(name.x)) %>% 
  arrange(desc(n)) %>% head(20)
topcolor <- top20theme %>% 
  inner_join(df_themes, by = c("name" = "name"))
g = df_themes %>% filter(name=='Clikits')
```

```{r}
topcolor %>% group_by(name, hex, h) %>%
  dplyr::summarize(n = sum(num_parts)) %>%
  ggplot(aes(1, n, fill=reorder(hex,h))) + 
  geom_bar(stat='identity', position = 'fill') +
          scale_fill_manual(values = pal) +
  labs(title ='Color Mix of Lego Themes with Most Sets', caption = "source: Rebrickable") +
  coord_flip() +
  facet_grid(name~., scales='free', switch="both") +
  theme_void( ) + 
  theme(axis.text.y=element_blank(),
        axis.text.x=element_blank(),
        strip.text.y=element_text(hjust=1),
        plot.margin=unit(c(1,0,0.5,0),"cm"),
        plot.title = element_text(hjust = -0.2)
        ) + theme() +
  my_theme() 

```
