---
title: "Where people are most interested in Data Visualization and Data Science"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse) # CSV file I/O, e.g. the read_csv function
#trend
library(gtrendsR)
#theme
my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(legend.text = element_text(color='white'),
    plot.title = element_text(face="bold", size=16,color='white', hjust=-0.5),
    plot.subtitle = element_text(color='white'),
    plot.caption = element_text(color='white'),
    strip.text = element_text(color='white'),
    axis.text = element_text(face="bold",color='white'),
    panel.grid = element_blank(),
    plot.background = element_rect(fill = 'grey21',color='white'))
}

```

##find top city hotspots and rising/breakout topics
```{r timeframe}
time=c("2014-01-01 2014-12-31",
       "2015-01-01 2015-12-31","2016-01-01 2016-12-31","2017-01-01 2017-08-31")

```

```{r fun1_city}
output <- NULL

hotspot = function(term, year){
  for (i in year) {
  gt=gtrends(term, time=i)
  
  top_city = head(gt$interest_by_city, 10)
  df_city=data.frame(city = top_city$location,
                     search_index = top_city$hits,
                     keyword = top_city$keyword)
  df_city$year=substr(i,1,4)
  output <- rbind(output, df_city)
  }
  return(output)
}
```

```{r fun2_trending_topic}
output <- NULL

trending_topic = function(term, year){
  for (i in year) {
  gt=gtrends(term, time=i)
  #find rising & breakout (viral topic)
  topic = gt$related_topics %>% 
      filter(related_topics!='top') %>% head(10)
  
  df_topic=data.frame(rising = topic$subject,
                      pct_growth = ifelse(topic$subject=="Breakout", 50,
                                as.numeric(gsub(",","",substr(topic$subject, 2, nchar(topic$subject)-1)))/100),
                      category = topic$related_topics,
                      name =  topic$value,
                      keyword = topic$keyword)
  df_topic$year=substr(i,1,4)
  output <- rbind(output, df_topic)
  }
  return(output)
}
```

```{r}
viz_city=hotspot("data visualization", time)
```

```{r}
viz_topic=trending_topic("data visualization", time)
```

```{r}
sci_city=hotspot("data science", time)
```

```{r}
sci_topic=trending_topic("data science", time)
```

##visualize topics with rising trends

```{r}
#function for properly order column in facet
ordered_facet_plot = function(df, color) {
  df = df %>%
  ungroup() %>%
  arrange(year, pct_growth) %>%
  mutate(order = row_number()) 

df%>%
  ggplot(aes(order, pct_growth)) + 
  geom_col(fill=color) +
  coord_flip() +
  facet_wrap(~year, scales="free") +
  my_theme() + 
  scale_x_continuous(
    breaks = df$order,
    labels = df$name
  )
}

```

```{r}
ordered_facet_plot(viz_topic, "yellow") + 
  labs(title = 'Rising search topics related to data visualization by year', 
       caption = 'source: Google Trends')
```


```{r}
ordered_facet_plot(sci_topic, "peachpuff") + 
  labs(title = 'Rising search topics related to data science by year', 
       caption = 'source: Google Trends')
```
```{r}
sessionInfo()
```

