---
title: ""
output: 
    html_document: 
      toc: true
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
# This is a code block
library(tidyverse) # CSV file I/O, e.g. the read_csv function
library(caret) # Data visualization
library(viridis)
library(RColorBrewer)
library(lubridate)
library(ggbeeswarm)
#visualization
library(formattable)
library(tweenr)
library(gganimate)
library(dplyr)
library(ggjoy)
#text
library(Hmisc)
library(spacyr)
#modeling
library(arules)
library(arulesViz)
spacy_initialize(python_executable = "/Users/hannah/anaconda/bin/python")
my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text = element_text(face="bold"),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    legend.position = 'None', legend.title = element_blank())
}

```

```{r input, message=FALSE}
start_eda=Sys.time()
#data https://www.kaggle.com/hugodarwood/epirecipes
epicurious_recipes_original <- read_csv("~/git_repo/opendata_viz/epicurious_recipes/epicurious_recipes.csv")

```

The tags contain:

* state name: Alabama
* drink name: bon apetit
* meal type: breakfast
* festival: 4th of jul
* season: summer
* diet type: soy free
* cooking method: braise
* ingredient: beef. 

We need to parse out these different entities

##rating vs protein, sodium, salt etc
```{r preprocess}
epicurious_recipes <- epicurious_recipes_original %>%
  mutate(rating_rounded = round(rating)) %>%
  mutate(rating_bkt = ifelse(rating_rounded>=4,"good",ifelse(rating_rounded==3,"ok","bad"))) %>%
  filter(fat<quantile(fat,.8, na.rm=T), calories<quantile(calories, .8, na.rm=T), protein<quantile(protein,.8, na.rm=T),sodium<quantile(sodium,.8, na.rm=T))


```
##rating vs nutrients
```{r}
content <- epicurious_recipes %>%
  select(c(calories:sodium, rating_bkt))%>%
  na.omit() %>%
  gather(key, value, -rating_bkt)

content$rating_bkt <- factor(content$rating_bkt, levels = c("bad", "ok", "good"))

#plot rating vs nutrients
ggplot(content, aes(x=value,y=rating_bkt, fill=rating_bkt, alpha=0.6)) + 
  geom_joy() + facet_wrap(~key, scales="free", nrow=2) +
  labs(title='recipe rating vs calories, fat and protein', caption='source: Epicurious')+
  my_theme()+guides(alpha=FALSE) 
```

```{r fun1_plot}
plot_density = function (df, facet) {
  ggplot(df, aes(x=value,y=facet, fill=facet, alpha=0.6)) + 
  geom_joy() + facet_wrap(~key, scales="free", nrow=2) +
  labs(title='recipe rating vs calories, fat and protein', caption='source: Epicurious')+
  my_theme()+guides(alpha=FALSE) 
}
```

```{r}
plot_density(content, content$rating_bkt)
```


##most common ingredient
```{r mostcommoningredient}
tag <- epicurious_recipes %>% 
  select(alabama:turkey) %>%
  summarise_all(sum) %>%
  gather(tag, count) %>%
  arrange(desc(count)) %>%
  mutate(tag = capitalize(tag))
```

```{r}
parsedtxt <- spacy_parse(tag$tag)
```

```{r fun2_bar}
tabularize = function(i) {
  i %>%
    select(-c(rating)) %>%
    summarize_all(sum) %>% 
    gather(category,count) %>%
    arrange(desc(count)) %>%
    formattable(list(count = color_bar("pink")),
    align = 'l')}
```

##rating vs state
```{r}
state <- parsedtxt %>% filter(entity == 'GPE_B')

df_state <- epicurious_recipes %>% 
  select(c(one_of(state$lemma),rating)) %>%
  select(-one_of('turkey','saffron','rye','chartreuse'))%>%
  na.omit()

df_state%>%select(-rating)%>%summarize_all(sum)

tabularize(df_state)
```

```{r fun3_transpose}

```


```{r}
plot_density(df_state, df_state$state)
```


##meal
```{r}
meal = c('breakfast','brunch','lunch','dinner')

df_meal <- epicurious_recipes %>% 
  select(c(one_of(meal),rating, calories:sodium)) %>%
  na.omit()

df_meal%>%select(-rating)%>%summarize_all(sum)
tabularize(df_meal)
```

```{r fun3_transpose_columns}
transpose_columns = function (x) {
df_total = x %>% 
  mutate(total = rowSums(select(., -c(rating:sodium))))%>%
  filter(total==1)
df_lean = df_total %>%select(-c(rating:total))

whichfield=function(x) colnames(df_lean)[[which(x==1)]]
df_lean$field=apply(df_lean,1,whichfield)

df_transposed=df_total%>%
  select(-c(1:4)) %>%
  bind_cols(df_lean) %>%
  select(c(calories:sodium, field))
return(df_transposed)
}
```

```{r}

```

```{r}
df_meal_nutrient <- transpose_columns(df_meal) %>%
  gather(key, value, -field)

df_meal_nutrient$field <- factor(df_meal_nutrient$field, 
                                 levels = c("dinner", "lunch", "brunch","breakfast"))
#plot rating vs nutrients

plot_density(df_meal_nutrient, df_meal_nutrient$field) +
  labs(title='meal vs calories, fat and protein', caption='source: Epicurious')
```


##season
```{r}
#filter for meal tagged to one season only
season = c('spring','summer','fall','winter')
df_season<- epicurious_recipes %>% 
  select(c(one_of(season),rating, calories:sodium)) %>%
  na.omit() #%>% 
  # mutate(total=spring+summer+fall+winter) %>% 
  # filter(total==1)

df_season%>%select(-rating)%>%summarize_all(sum)
tabularize(df_season)
```
```{r}
df_season_nutrient <- transpose_columns(df_season) %>%
  gather(key, value, -field)

df_season_nutrient$field <- factor(df_season_nutrient$field, 
                                 levels = c("winter", "fall", "summer","spring"))
#plot rating vs nutrients

plot_density(df_season_nutrient, df_season_nutrient$field) +
  labs(title='seasonal meal vs calories, fat and protein', caption='source: Epicurious')
```


##holiday
```{r}
holiday = c('christmas','fourth of july','passover','thanksgiving','easter','new year\'s eve')
df_holiday<- epicurious_recipes %>% 
  select(c(one_of(holiday),rating, calories:sodium)) %>%
  na.omit()


tabularize(df_holiday)
```
```{r}
df_holiday_nutrient <- transpose_columns(df_holiday) %>%
  gather(key, value, -field)

# df_holiday_nutrient$field <- factor(df_holiday_nutrient$field, 
#                                  levels = c("winter", "fall", "summer","spring"))
#plot rating vs nutrients

plot_density(df_holiday_nutrient, df_holiday_nutrient$field) +
  labs(title='holiday meal vs calories, fat and protein', caption='source: Epicurious')
```


##ingredients

```{r}
df <- epicurious_recipes %>% 
  select(-one_of(state$lemma, meal, season)) %>%
  na.omit()
```

```{r}
data = df%>% select(rating_bkt,alcoholic:zucchini)%>%
       mutate_all(funs(factor(.))) 
```


```{r}
rules <- apriori(data, parameter=list(support=0.01, confidence=0.5),
                 appearance = list(rhs=c("rating_bkt=good"),
                                   default="lhs"))
inspect(head(sort(rules, by ="lift"),5))
```
```{r}
plot(rules, method="grouped")
```


