---
title: ""
output: 
    html_document: 
      toc: true
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
# This is a code block
library(readr) # CSV file I/O, e.g. the read_csv function
library(tidyr)
library(countrycode)
library(ggplot2) # Data visualization
library(viridis)
library(RColorBrewer)
library(lubridate)
library(tweenr)
library(gganimate)
library(animation)
library(ggtern)
library(dplyr)
```

```{r}
# my.list <- split(df, df$metrics)
# tf <- tween_states(my.list, tweenlength= 2, statelength=3, ease=rep('cubic-in-out',51),nframes=10)
# dtf <- data.table(tf)
# ```
# ```{r}
# p <- df %>%  
#   ggplot(aes(Id, value, frame = metrics)) + 
#   geom_bar(stat='identity',color='white') + 
#   coord_flip() + 
#   theme_minimal()
#  
#   gganimate(p,'index.gif')
```
```{r}
# n_df <- df %>%
#   group_by(metrics) %>%
#   nest() 
# 
# tween_df <- tween_states(n_df$data, tweenlength = 1,
#   statelength = 0.5, ease = "sine-out", nframe = 200) %>%
#   as.tibble()
```
```{r}

```

```{r}
Indicators$region= countrycode(Indicators$CountryName, 'country.name', 'region')
Indicators$code= countrycode(Indicators$CountryName, 'country.name', 'iso2c')
```



```{r}
df_energy = Indicators %>% 
  filter(grepl('ZS',IndicatorCode)) %>%
  filter(grepl("Electricity production from oil, gas and coal sources|Electricity production from hydroelectri| nuclear sources|renewable sources",IndicatorName)) %>%
  mutate(eletricity_source = ifelse(grepl('oil, gas and coal ',IndicatorName),'Nonrenewable',
                ifelse(grepl('nuclear',IndicatorName),'Nuclear','Renewable'))) %>% 
  group_by(CountryName, region, eletricity_source, Year) %>%
  #group_by(eletricity_source) %>%
  summarize(Value = sum(Value)) %>%
  spread(eletricity_source, Value)
```

```{r}
my_theme <- function(base_size = 10, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=14),
    axis.text = element_text(face="bold"),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    panel.grid.minor = element_blank(),
    legend.position="bottom", legend.title=element_blank(),legend.text=element_text(size=6)
    ) 
}
```

```{r ter}
#year 1995 - 2012 has consistent number of records
sample=df_asia %>% filter(Year=='2012') 

ternary_plot = function(i) {
  ggtern(i, aes(x = Nuclear, y = Nonrenewable, z = Renewable, col=region)) +
    geom_point(shape = 17, alpha=0.8, size = 5) + 
    geom_Lmark(alpha=0.1) +
    my_theme()}

```

```{r asia}
df_asia = df_energy %>% filter(Year=='2012', grepl('Asia|Australia and New Zealand',region), !grepl('Western Asia',region))

ternary_plot(df_asia) + 
  geom_text(aes(label= ifelse(Nuclear>quantile(Nuclear, 0.9), CountryName,"")), size=2,hjust=-0.2) + 
    scale_x_continuous(expand = c(.3, .0))
```

```{r eu}
sample_eu <- df_energy %>% 
  filter(Year=='2012', grepl('Europe|Western Asia', region))

ternary_plot(sample_eu) + 
  geom_text(aes(label= ifelse(Nuclear >= quantile(Nuclear, 0.9), CountryName,"")), size=2,vjust=2) + 
    scale_x_continuous(expand = c(.3, .0)) 
```



```{r na}
sample_americas <- df_energy %>% 
  filter(Year=='2012', grepl('America|Caribbean',region))
ternary_plot(sample_americas) + 
  geom_text(aes(label= ifelse(Nuclear >= quantile(Nuclear, 0.9),CountryName,"")), size=2,vjust=2) + 
    scale_x_continuous(expand = c(.3, .0))
```

```{r}
sample_africa <- df_energy %>% 
  filter(Year=='2012', grepl('Africa',region))
ternary_plot(sample_africa) + 
  geom_text(aes(label= ifelse(Nuclear >= 5 ,CountryName,"")), size=2,vjust=5.1) + 
    scale_x_continuous(expand = c(.3, .0))
```


```{r euanimated}
sample_eu <- df_energy %>% 
  filter(grepl('Europe',region), Year>='2005',Year<'2013')

p <-  ggtern(sample_eu, aes(x = Nuclear, y = Nonrenewable, z = Renewable, col=region, frame=.Year)) +
    geom_point(shape=16, alpha=0.8)
gganimate(p, "ggtern_tween.gif")

```