---
title: ""
output: 
    html_document: 
      toc: true
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
# This is a code block
library(readr) # CSV file I/O, e.g. the read_csv function
library(tidyr)
library(ggplot2) # Data visualization
library(viridis)
library(RColorBrewer)
library(lubridate)
library(plotly)
library(dplyr)
library(ggbeeswarm)
library(countrycode)
library(stringr)
```

```{r input, message=FALSE}
#kaggle data 2016-17 https://www.kaggle.com/ikalats/TechnologyPriceIndex
df<- read_csv("gadgetprice.csv")
# purchasing power 2014 http://www.nationmaster.com/country-info/stats/Cost-of-living/Local-purchasing-power#
purchasingpower <- read_csv("purchasingpower.csv")
glimpse(df)
```

```{r preprocessing, message=FALSE}
#remove thousands separator
#dollar sign need to be escaped
gadget <- df %>% 
  filter(Country!='Venezuela')%>%
  select(-`Portable charger`) %>%
  gather(key, value, -Rank, -Country)%>%
  mutate(value=gsub(",","",value), value=gsub("\\$","",value))%>%
  mutate(value=as.numeric(value), region=countrycode(Country, 'country.name', 'continent')) %>%
  mutate(region = ifelse(Country=='Uruaguay','Americas',region))
#write.csv(gadget,'gadget.csv')
```
```{r, message=FALSE}
gadget<-gadget %>%
  group_by(key) %>%
  mutate(maxmin = ifelse(value==max(value)|value==min(value),value, as.numeric(NA))) %>%
  mutate(maxmincountry = ifelse(is.na(maxmin),"",Country))
```

```{r}
gadget %>%
ggplot(aes(key, value)) + 
geom_beeswarm(aes(col=region, alpha=0.9)) + 
theme_minimal() +
coord_flip() +
theme(axis.title.y=element_blank(),axis.title.x=element_blank(),
      plot.title=element_text(face="bold", size=16),
      axis.text=element_text(face="bold"),
      text=element_text(family="Helvetica"),
      plot.background = element_rect(fill = 'ghostwhite',color='white')) +
  labs(title = "Price of gadgets",
        subtitle = "countries with highest and lowest price (USD) in gadgets")+
  geom_text(aes(label=str_wrap(maxmincountry, 10)), cex=3, vjust=-0.5) +
  guides(alpha=FALSE)
```

```{r globalmedianprice}
medianprice = gadget %>% 
  group_by(key) %>%
  mutate(medprice = median(value)) %>% 
  ungroup() %>%
  mutate(above_global_median = ifelse(value>=medprice, 1, 0)) %>%
  group_by(region, key) %>%
  summarize(pct = mean(above_global_median), group = 'above') 
medianprice = medianprice %>% mutate(pct = - (1-  pct), group = 'below') %>% rbind(medianprice)

medianprice %>% ggplot(aes(x=region, y=pct, fill=region)) + 
  facet_wrap(~key)+
  geom_bar(stat="identity", position="identity", width=0.8) + 
  geom_abline(aes(slope=0, intercept=0)) + 
  theme_minimal() +
  theme(axis.title.y=element_blank(),axis.title.x=element_blank(),
      plot.title=element_text(face="bold", size=16),
      axis.text.x=element_blank(),
      text=element_text(family="Helvetica"),
      plot.background = element_rect(fill = 'ghostwhite',color='white')) +
  labs(title = "Gadget price benchmark by continents",
         subtitle = "Regional level % of countries with price above and below global median, each bar adds up to one") 
```

```{r purchasingpower}
library("scales")
library(ggrepel)
temp = gadget%>%
  group_by(Country, region) %>%
  mutate(value2=rescale(value))%>%
  summarize(gadgetpriceindex = mean(value2)) %>%
  ungroup %>%
  mutate(gadgetpriceindex = rescale(gadgetpriceindex))
purchasingpower <- purchasingpower %>% 
  mutate(Country = recode_factor(Country, "United States"="USA", "United Kingdom"="UK",
                                 "Uruguay"="Uruaguay"))%>% 
  mutate(purchasingpower = rescale(Amount)) 
combined = temp %>% left_join(purchasingpower, by='Country')

combined%>%
ggplot(aes(gadgetpriceindex, purchasingpower)) + 
geom_point(aes(color=region)) +
theme_minimal() +
geom_text_repel(aes(label=Country, color=region), size=3) +
  theme(
      plot.title=element_text(face="bold", size=16),
      text=element_text(family="Helvetica"),
      plot.background = element_rect(fill = 'ghostwhite',color='white')) +
  labs(title = "Gadget price vs purchasing power by country") 
```

```{r}
sessionInfo()
```

