---
title: "pantheon_popularity_index"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error=F, warning=F)
library(tidyverse) # CSV file I/O, e.g. the read_csv function
library(RColorBrewer)
library(plotly) 
library(ggimage)
#date
library(lubridate)
#machinelearning
library(caret)
#text
library(tidytext)
#3d
library(threejs)
#animate
library(tweenr)
library(gganimate)
#theme
my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text.y = element_blank(),
    panel.grid = element_blank(),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    legend.position = 'None', legend.title = element_blank())
}

```

## Load data

```{r input}
pantheon_popularity_index <- read.csv("~/git_repo/opendata_viz/pantheon_popularity_index/pantheon_popularity_index.csv", stringsAsFactors=FALSE)

pantheon_i50 <- pantheon_popularity_index %>%
  filter(city %in% c('Rome', 'Paris', 'New York'),
         article_languages>=50) %>%
  mutate(birth_year = (birth_year))
```

```{r tableau}
#calculate x, y coordinates
pantheon_i50_rome <- pantheon_i50 %>%
  filter(city %in% c('Rome')) %>%
  arrange(desc(historical_popularity_index)) 

pantheon_i50_rome$ID <- seq.int(nrow(pantheon_i50_rome))

pantheon_i50_rome <- pantheon_i50_rome %>%
  mutate(x = article_languages * sin(2*pi*ID/nrow(pantheon_i50_rome)),
         y = article_languages * cos(2*pi*ID/nrow(pantheon_i50_rome)))

pantheon_i50_rome[72:142,]=pantheon_i50_rome
pantheon_i50_rome[72:142, "ID"]=seq.int(71)
pantheon_i50_rome[72:142, "x"]=0.0
pantheon_i50_rome[72:142, "y"]=0.0
pantheon_i50_rome[72:142, "full_name"]="origin"

write.csv(pantheon_i50_rome,'s.csv')
```

```{r fig.width=800, fig.height=200}
#to-do: fast forward time
#'London', 'Los Angeles','Istanbul'

pantheon_i50 %>%
  ggplot()  +
  #historical_popularity_index/20
  geom_segment(aes(y = 0, 
                   x = birth_year, 
                   yend = article_languages, 
                   xend =  birth_year),
                   color = "lightgrey", size=0.5) +
  geom_segment(aes(y = max(article_languages)+20, 
                   x = birth_year, 
                   yend = max(article_languages)+25, 
                   xend =  birth_year),
                   color = "lightgrey", size=0.5) +
  #use marginal border to different gender
  geom_point(data = subset(pantheon_i50, sex=='Female'),
             aes(x=birth_year, 
             y=article_languages, 
             size=historical_popularity_index/20+0.2),
             col="black") +
  geom_point(aes(x=birth_year, 
             y=article_languages, 
             col=domain, 
             size=historical_popularity_index/20),
             alpha=0.8) +
  #geom_image(aes(image=image), size=.05) +
  coord_polar() +
  theme_void() +
  scale_x_continuous(breaks=seq(min(pantheon_i50$birth_year),max(pantheon_i50$birth_year),100)) +
  facet_grid(.~city, scales="free")

```





