---
title: "Quantifying my instagram posts with Google Vision"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(lubridate)
#instagram scrapping
library(instaR)
library(ggimage)
```

## Google Vision API

```{r google_authen}
creds = fromJSON('other_secret.json')
options("googleAuthR.client_id" = creds$installed$client_id)
options("googleAuthR.client_secret" = creds$installed$client_secret)
options("googleAuthR.scopes.selected" = c("https://www.googleapis.com/auth/cloud-platform"))
googleAuthR::gar_auth()
```


```{r insta_authen}
app_id=" "
app_secret=" "
token <- instaOAuth(app_id, app_secret, scope = c("basic", "public_content"))
```

```{r scrap_recent}
recentphoto <- getUserMedia("h_yan2", token, n = 20, 
                            folder = "insta_tagging", 
                            userid = NULL, verbose = TRUE)
```
##label detection

```{r loop}
files <- list.files(path="insta_tagging", pattern="*.jpg", full.names=T, recursive=FALSE)
label <- sapply(files, function(x) {
    t <- getGoogleVisionResponse(x, feature = 'LABEL_DETECTION')
    list(t$description[1], t$description[2])
}) 
df_label <- t(as.data.frame(label))
```


```{r str}
library(stringr)
df_label$id <-sapply(df_label$X1, function(x){str_match(x, "g/(.*?)_h")[2]})
```


```{r join}
df_join <- recentphoto %>%
  left_join(df_label, by = "id")
```
```{r}
write.csv(df_join, 'df_join.csv')
```

