---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error=F, warning=F)
library(tidyverse) # CSV file I/O, e.g. the read_csv function
library(RColorBrewer)
#library(plotly) #contain hex to RGB conversion
#date
library(lubridate)
#world prison brief
library("prisonbrief")
#map
library(sf)
library(rworldmap)
#theme
my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text = element_text(face="bold"),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    legend.position = 'None', legend.title = element_blank())
}

```

## Load data

```{r}
df_stats<- wpb_table(region = "All")
write.csv(df_stats, 'df_prison_stats.csv')
```

```{r}
n <- joinCountryData2Map(df_stats, joinCode="ISO2", nameJoinColumn="iso_a2")
mapCountryData(n, 
               nameColumnToPlot="prison_population_rate", 
               mapTitle="Prison population rate per 100,000 people")
```
```{r}
barplotCountryData(n, 
               nameColumnToPlot = "prison_population_rate", 
               main = "Prisoner population rate  per 100K of the national population",
               colourPalette=head(brewer.pal(10,"YlOrRd"),5),
               na.last = NA,
               catMethod = "quantiles",
               numPanels = 3)
```
```{r}
barplotCountryData(n, 
               nameColumnToPlot = "prison-population-total", 
               main = "Prisoner population",
               colourPalette=head(brewer.pal(10,"Blues"),5),
               na.last = NA,
               catMethod = "quantiles",
               numPanels = 3)
```

```{r}
mapCountryData(n, 
               nameColumnToPlot="female-prisoners", 
               mapTitle="female-prisoners")
```
```{r}
barplotCountryData(n, 
               nameColumnToPlot="female-prisoners", 
               main = "Female Prisoner Ratio",
               colourPalette=head(brewer.pal(10,"PuRd"),5),
               na.last = NA,
               catMethod = "quantiles",
               numPanels = 3,
               cex = 1)
```
```{r}
mapCountryData(n, 
               nameColumnToPlot="foreign-prisoners", 
               mapTitle="foreign-prisoners")
```
```{r}
barplotCountryData(n, 
               nameColumnToPlot="foreign-prisoners", 
               main = "Foreign Prisoner Ratio",
               colourPalette=head(brewer.pal(12,"YlGnBu"),5),
               na.last = NA,
               catMethod = "quantiles",
               numPanels = 3,
               cex = 1)
```
```{r}
barplotCountryData(n, 
               nameColumnToPlot="occupancy-level", 
               main = "Prison Occupancy Level",
               colourPalette=head(brewer.pal(12,"YlGn"),5),
               na.last = NA,
               catMethod = "quantiles",
               numPanels = 3,
               cex = 1)
```
```

