---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse) # CSV file I/O, e.g. the read_csv function
library(plyr)
library(stringr)
library(RColorBrewer)
#tesseract
library(deldir)
library(rvest)
library(rmapzen)
#theme
my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text = element_text(face="bold"),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    legend.position = 'None', legend.title = element_blank())
}

```

## read webpage

```{r input}
#Specifying the url for desired website to be scrapped
url <- 'https://guide.michelin.sg/en/2017-MICHELIN-guide-Singapore-full-results-restaurants'
#Reading the HTML code from the website
webpage <- read_html(url)
```

```{r}
st_page %>% 
  html_nodes(".odd > h3:nth-child(7) > span:nth-child(1) > span:nth-child(1)") %>% html_text()
```

## scrap 

```{r pre_process}
st_page <- read_html("http://www.straitstimes.com/lifestyle/food/full-list-of-michelin-starred-restaurants-for-2017")

full_list <- st_page %>%
   html_nodes("h3") %>%
  html_text() %>% as.data.frame() 

restaurants <- st_page%>%
  html_nodes("#docs-internal-guid-765e48e9-f34b-7c88-5d95-042a93fcfda3") %>%
  html_text() %>% as.data.frame()  %>% mutate(.=as.character(.))
```



## extract info from text
```{r}
address <- restaurants %>% 
  mutate(addr = as.character(lead(.,1)))%>% 
  filter(grepl('^\\d',.)) %>%
  mutate(idx = as.numeric(str_extract(as.character(.), '^\\d+')),
         name = trimws(str_replace(as.character(.), '^\\d+.','')),
         addr = str_replace(addr, 'Address:','')
         ) %>%
  separate(name, into = c("restaurant", "locale"), sep = ",")%>%
  select(-.) %>%
  filter(addr!=' ')
```
```{r}
#some address are missing, some manual cleaning
write.csv(address,'address.csv')
```


```{r namelist}
tbls <- html_nodes(webpage, "table")%>%
        .[1:3] %>%
        html_table(fill = TRUE) %>%
        rbind.fill() 
colnames(tbls) = c('restaurant' ,'cuisine')
tbls <- tbls %>%
        mutate(stars = c(rep(3,2), rep(2, 8), rep(1,31)),
               restaurant=trimws(toupper(restaurant))) %>%
        filter(restaurant!='RESTAURANT 餐馆') 
write.csv(tbls,'cuisines.csv')
```

```{r}
joined <- address %>% left_join(tbls)
```


