---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/hannah/git_repo/opendata_viz/r_stackoverflow")
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(dplyr)
library(tidyr)
library(reshape2)
library(RColorBrewer)
library(lubridate)
library(tidytext)
library(ggnetwork)
library(ggraph)
library(igraph)
library(sqldf)
```

## Load data

```{r input}
#python data from https://www.kaggle.com/stackoverflow/pythonquestions
df<-read_csv('python_stackoverflow.csv') %>%
  filter(!grepl('python',Tag))

```
```{r}
py_tag_freq <- df %>% 
  group_by(Tag) %>%
  count(Tag, sort=T)

py_tag_freq %>% head%>% 
  ggplot(aes(reorder(Tag, n), n)) + 
  geom_bar(stat='identity', width=0.5) + 
  coord_flip() + 
  ggtitle("") +
  theme_minimal() +
  theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
  plot.title = element_text(face="bold", size=16),
  axis.text = element_text(face="bold"),
  text = element_text(family = "Helvetica"),
  plot.background = element_rect(fill = 'ghostwhite',color='white')) +
  labs(title = "Top tags for Python questions on Stackoverflow",
  subtitle = "")
```

```{r}
co_occur = sqldf("SELECT a.Tag a, b.Tag b, COUNT(*) cnt
FROM  df a 
JOIN df b 
ON b.Id = a.Id AND b.Tag > a.Tag
GROUP BY a.Tag, b.Tag")
```


```{r}
g <- co_occur %>% 
  filter(cnt>800)  %>%
  graph_from_data_frame() 

V(g)$Popularity <- degree(g, mode = 'in')
#V(g)$size=tag_freq[match(V(g)$name,tag_freq$Tag), 2]

```

```{r ggraph}
g %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = cnt), show.legend = FALSE) +
  geom_node_point(color = "darkgreen",aes(size = Popularity)) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void() + 
  theme(legend.position = 'None') 
```


```{r community}
clp <- cluster_label_prop(g)
class(clp)
V(g)$community <- clp$membership
plot(clp, g,
     vertex.label = ifelse(degree(g) > 3,V(g)$name, NA),
     edge.arrow.mode=0, 
     vertex.label.color="black", vertex.label.font=2,
     main = 'Related Python questions on Stackoverflow')

```

```{r}
#how to vary node size
#how to filter out satellites (both nodes on a edge has one connection only), community with only two vertex
```


```{r commontopic}
library(ggrepel)
common = py_tag_freq %>%inner_join(r_tag_freq, by='Tag')
med_r=mean(r_tag_freq$n)
med_py=mean(py_tag_freq$n)
common_freq = common %>%
  filter(n.x>med_py, n.y>med_r)

common_freq %>%
  ggplot(aes(n.x, n.y)) + 
  geom_point() + 
  ggtitle("") +
  geom_text_repel(aes(label = ifelse(n.x>9000|n.y>2000, Tag,NA), vjust=-0.3))+
  theme_minimal() + 
  theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
  plot.title = element_text(face="bold", size=16),
  axis.text = element_text(face="bold"),
  text = element_text(family = "Helvetica"),
  plot.background = element_rect(fill = 'ghostwhite',color='white')) +
  labs(title = "Common tags among R and Python questions",
  subtitle = "")
```



