---
title: "Occupation of TED Speakers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error=F, warning=F)
library(tidyverse) # CSV file I/O, e.g. the read_csv function
library(RColorBrewer)
library(plotly) #contain hex to RGB conversion
#date
library(lubridate)
#network
library(sqldf)
library(igraph)
library(ggraph)
#theme
my_theme <- function(base_size = 12, base_family = "Helvetica"){
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face="bold", size=16),
    axis.text = element_text(face="bold"),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    legend.position = 'None', legend.title = element_blank())
}

```

Based on refreshed data on kaggle (till 2017)

```{r echo = FALSE}
#https://www.kaggle.com/rounakbanik/ted-talks
ted_original <- read_csv("~/git_repo/opendata_viz/TED/ted_new.csv")

ted <- ted %>%
  mutate(film_date = as.Date(as.POSIXct(film_date, origin="1970-01-01"))) %>%
  mutate(film_year = year(film_date)) %>%
  mutate(year = ifelse(film_year<=2008,'<2008',film_year)) 
```
# Pre-processing
Split speaker occupation by /or,or;

```{r}
patternreplace = function(x, patterns, replacements = patterns, fill = NA, ...)
  {
stopifnot(length(patterns) == length(replacements))
ans = rep_len(as.character(fill), length(x))    
empty = seq_along(x)

for(i in seq_along(patterns)) {
greps = grepl(patterns[[i]], x[empty], ... , ignore.case = T)
ans[empty[greps]] = replacements[[i]]  
empty = empty[!greps]
}
return(ans)
}

top_occupation <- ted %>%
  count(speaker_occupation, sort=T) %>%
  head(30)

from = c(top_occupation$speaker_occupation,
         'Engineer','Futurist','Mathematician')
to = c("writer", "artist/designer","artist/designer","journalist",
  "entrepreneur","architect","inventor","psychologist","photographer","filmmaker",
  "scientist/technologist","writer","economist","educator","scientist/technologist",
  "scientist/technologist","philosopher","scientist/technologist","scientist/technologist",
  "musician", "activist","visionary","scientist/technologist", "astronomer", "behavioral economist","artist/designer", "historian","scientist/technologist","philanthropist","writer",
  "scientist/technologist","futurist","scientist/technologist"
)
```

```{r}
occupation <- ted%>%
  select(speaker_occupation, name, views, year) %>% 
  mutate(occupation=strsplit(speaker_occupation, ",|;|/")) %>% 
  unnest(occupation)%>%
  mutate(occupation = trimws(tolower(occupation))) %>%
  mutate(occupation = ifelse(grepl('co-founder|founder|ceo', occupation ),'entrepreneur',occupation)) %>%
  mutate(occupation2 = patternreplace(occupation, from, to)) %>%
  mutate(occupation2 = ifelse(is.na(occupation2), occupation,  occupation2))
  
```


```{r}
co_occur = sqldf("SELECT a.occupation2 a, b.occupation2 b, COUNT(*) cnt
FROM  occupation a 
JOIN occupation b 
ON b.name = a.name AND b.occupation2 > a.occupation2
GROUP BY a.occupation2, b.occupation2")

g <- co_occur %>% 
  graph_from_data_frame() 

V(g)$Popularity <- degree(g)
length(V(g)$name)
E(g)$year <- as.character(E(g)$year)
```
## Speakers wearing multiple hats

```{r ggraph}

g %>%
  ggraph(layout = 'fr') +
  geom_edge_link(aes(edge_alpha = cnt),edge_colour = 'white',  show.legend = FALSE) +
  geom_edge_density(aes(fill = 'white')) + 
  geom_node_point(color = "white",aes(size = Popularity)) +
  geom_node_text(color = "ghostwhite", aes(label = ifelse(Popularity>=10, V(g)$name,'')), size=3, repel = TRUE) +
  theme_void() + 
  theme(legend.position = 'None',
        plot.background = element_rect(fill = '#300961',color='grey'),
        plot.margin=unit(c(1.2,1.2,1.2,1.2),"cm")) + coord_equal()

```

## Find connected occupations
zoom in on data visionaries (flower spoke plot)

```{r}
adjacent_vertices(g, 111)
```
## Zoom in to occupations linked to more than one other occupations
```{r}
# distribution of degree centrality
hist(V(g)$Popularity)
mean(V(g)$Popularity)
V(g)[V(g)$Popularity>20]

#refer a node by its idx
E(g) [ from(4) ]

#refer a node by its name
idx <- match("scientist/technologist", V(g_sub)$name)
E(g_sub) [ from(idx) ]
E(g_sub) [ to(idx) ]

#filter a node by degree centrality
E(g)[inc(V(g)$Popularity>20)]
```
Filter for high degree centrality nodes and their edges
```{r}
g_sub=subgraph.edges(g, E(g)[inc(V(g)$Popularity>20)]) 

g_sub%>%
  ggraph(layout = 'fr') +
  geom_edge_link(edge_colour = 'white',  show.legend = FALSE) +
  geom_edge_density(aes(fill = 'white')) + 
  geom_node_point(color = "white", size=5) +
  geom_node_text(color = "ghostwhite", aes(label = ifelse(Popularity>=2&Popularity<20, V(g_sub)$name,'')), size=2, repel = TRUE) +
  geom_node_text(color = "white", aes(label = ifelse(Popularity>=20, V(g_sub)$name,'')), size=3, fontface='bold', repel = TRUE) +
  theme_void() + 
  theme(legend.position = 'None',
        plot.background = element_rect(fill = '#300961',color='grey'),
        plot.margin=unit(c(1.2,1.2,1.2,1.2),"cm")) + coord_equal()
```

```{r}
g_multi %>%
  ggraph(layout = 'fr') +
  geom_edge_link(aes(edge_alpha = cnt),edge_colour = 'white',  show.legend = FALSE) +
  geom_edge_density(aes(fill = 'white')) + 
  geom_node_point(color = "white",aes(size = Popularity)) +
  geom_node_text(color = "ghostwhite", aes(label = ifelse(Popularity>=10, V(g)$name,'')), size=3, repel = TRUE) +
  facet_edges(~year, nrow = 5) +
  theme_void() + 
  theme(legend.position = 'None',
        plot.background = element_rect(fill = '#300961',color='grey'),
        plot.margin=unit(c(1.2,1.2,1.2,1.2),"cm")) + coord_equal()
```




turn everyone with a creativity into stars


