---
title: "image_to_text"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(abind)
library(imager)
library(grid)
setwd("/Users/hannah/git_repo/opendata_viz/first_women")
```

## load images of the featured humans

```{r input}
files <- list.files(path="images", pattern="*.jpg", full.names=T, recursive=FALSE)
list_of_images = lapply(files, load.image) 
```

```{r clean}
#extract name from file names
file_name <- data.frame(files)
file_name$name  <- gsub(".*images/*|(-|_)*(luisa|time|\\d).*", "",files)
file_name$name <- gsub("(-|_)"," ", file_name$name)
```



## scrap text related to the featured humans

```{r scrap}
library(rvest)
page <- read_html("http://time.com/collection/firsts/")
page_txt<-page %>%
  html_nodes("._2Srftrln") %>%
  html_text() %>% as.data.frame() 


## clean up description

colnames(page_txt)='alltxt'
desc <- page_txt %>%
  mutate(alltxt=as.character(alltxt)) %>%
  # find 3rd captal letter to split out title which are two words
  mutate(desc = sub("(([A-Z][^A-Z]+){2})(.*)","\\1+\\3",alltxt)) %>%
  separate(desc, into = c('title','txt'), sep="\\+") %>%
  select(-alltxt) %>%
  mutate(txt = gsub("Watch","",txt)) %>%
  mutate(txt = gsub("Read","",txt)) %>%
  #split out name
  mutate(txt = gsub('First','@First',txt)) %>%
  separate(txt, into = c('name','first'), sep="@") %>%
  arrange(name) %>%
  filter(!is.na(first)) %>%
  #extract descriptor between 'the first' and 'to/in'
  mutate(descriptor = gsub(".*First\\s*|\\s[(to)(in)(with)(of)(and)(CEO)(U.S.)(person)].*", "", first))
```
## background and achievements
```{r}
title <- merge %>%
  select(title, descriptor, name, age_bkt) %>%
  mutate(descriptor = ifelse(grepl('((^-)American)|tennis',descriptor),'woman',descriptor)) %>%
  mutate(descriptor = ifelse(grepl('Muslim',descriptor),'Muslim',descriptor)) %>%
  arrange(age_bkt)
write.csv(title, 'title.csv')
```




## scrap more info from wikipedia - age
```{r}
#make tibble and bind df
desc$name_search=gsub(" ","_",desc$name)

scrap_age <- function(i) {
  url <- paste0("https://en.wikipedia.org/wiki/", i)
  page <- read_html(url)
  
  page_txt<-page %>%
    html_nodes(".ForceAgeToShow") %>%
    html_text()
  
  return(tibble(page_txt=page_txt,
                name=i))
}
age <- desc$name_search%>%
  map_dfr(scrap_age) 
age_bkt= age%>% mutate(age = as.numeric(gsub("\\(age\\s|\\)", "", page_txt))) %>%
  mutate(age_bkt = cut(age, breaks=c(0,20,40,60,80,100)))
```

```{r}
#most name matches, a few have spelling difference
merge= desc %>% mutate(name = tolower(name))%>% 
  left_join( file_name, on = 'name') %>%
  left_join(age_bkt, by = c("name_search"="name"))
```

## convert colored photo to text collages 
```{r}
#source: http://giorasimchoni.com/2017/07/09/2017-07-09-read-my-face/

drawImageWithText <- function(img, text, thresh, name, color = FALSE,
                              fontSize = 12, 
                              fileName = paste0(name, ".png"),
                              resize = TRUE, saveToDisk = FALSE) {
  
  if (color) {
    if (spectrum(img) == 1) {
      warning("Image is in grayscale mode, setting color to FALSE.")
      color = FALSE
    }
  }
  
  text <- paste(text, collapse = " ")
  text <- str_replace_all(text, "\n+", " ")
  text <- str_replace_all(text, " +", " ")
  
  text <- str_split(text, "")[[1]]
  
  if (resize) img <- resize(img, 700, 500)
  
  imgMat <- img %>%  as.array() %>% adrop(3) %>% aperm(c(2, 1, 3))
  
  imgGSMat <- img %>% grayscale %>% as.matrix %>% t()
  #simplified original code to even out letters
  #fatChars <- c(LETTERS[-which(LETTERS == "I")], "m", "w", "@")
  fatChars <- NA
  #skinnyChars <- c("l", "I", "i", "t", "'", "f")
  skinnyChars <- NA
  
  if (saveToDisk) png(fileName, width(img), height(img))
  
  grid.newpage()
  
  counter <- 0
  
  for (i in seq(1, nrow(imgGSMat) - fontSize, fontSize + 1)) {
    for (j in seq(1, ncol(imgGSMat) - fontSize, fontSize)) {
      if (imgGSMat[i, j] < thresh) {
        counter <- ifelse(counter < length(text), counter + 1, 1)
        beforeLastChar <- ifelse(counter > 2, lastChar, " ")
        lastChar <- ifelse(counter > 1, char, " ")
        char <- text[counter]
        grid.text(char,
                  x = 0.01 + j/ncol(imgGSMat) +
                    0.004 * (lastChar %in% fatChars) -
                    0.003 * (lastChar %in% skinnyChars) +
                    0.003 * (beforeLastChar %in% fatChars) -
                    0.002 * (beforeLastChar %in% skinnyChars),
                  y = 1 - i / nrow(imgGSMat) - 0.01,
                  gp = gpar(fontsize = fontSize, col = ifelse(!color, 
                                                              "black",
                                                              rgb(imgMat[i, j, 1],
                                                                  imgMat[i, j, 2],
                                                                  imgMat[i, j, 3]))),
                  just = "left")
      }
    }
  }
  
  if (saveToDisk) suppressMessages(dev.off())
}
```


```{r plot}
#plot merged ones first, clean up the name later 
merged = merge %>% filter(!is.na(title))

for (i in 1:nrow(merged)) {
drawImageWithText(load.image(as.character(merged$files[i])), merged$first[i], 
                  thresh = 0.9, name=merged$name[i], color = TRUE,fontSize = 6, saveToDisk = T)
}
```

