---
title: Text analysis of wine tasting notes
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(dplyr)
library(tidyr)
library(magrittr)
#text
library(tidytext)
library(spacyr)
library(cleanNLP)
init_spaCy(model_name = "en")
#library(topicmodels)
```

## Load data

```{r input}
wine <- read_csv("~/git_repo/opendata_viz/wine/wine.csv")
```

```{r variety}
variety <- wine %>% group_by(country, province) %>%
  dplyr::count(variety, sort=T) %>% 
  top_n(1)
```
```{r producer}
top_province <- wine %>% 
  dplyr::group_by(country, province) %>%
  dplyr::summarize(n=n()) %>%
  arrange(-n) %>%
  head(9)
```

```{r topproduce}
top_produce <- wine %>% 
  group_by(variety) %>%
  summarize(n=n()) %>%
  arrange(-n) %>%
  head(9)
```

```{r}
wine_select <- wine %>% 
  dplyr::filter(province %in% top_province$province) %>%
  dplyr::select(province, country, description, region_1, variety) %>%
  dplyr::mutate(id = row_number())

#keep data of province to be joint to parsed text
wine_index <- wine_select %>%
  dplyr::select(id, province,variety)
```

```{r}
#run_annotators works on files path of csv, or df (must state as_strings = TRUE)
wine_anno <-  get_combine(run_annotators(wine_select$description, as_strings = TRUE)) 
```
```{r}
wine_nlp <- wine_anno %>%
  filter(upos == 'ADJ', pos=='JJ') %>%
  filter(!lemma %in% c('black','red','green','white','dark','yellow'),
           word!='dried') %>%
  left_join(wine_index)
```


```{r}
top_word <- head(sort(table(wine_nlp$word), decreasing=T),20)

    #   dry      ripe     sweet      rich      good      soft      full     crisp 
    # 15810     14592     13196     12951      9651      8674      6487      6354 
    # fresh    tannic    little      fine     spicy       new     smoky   complex 
    #  6314      6194      5197      5144      4298      4207      4201      4177 
    # clean    smooth    bright delicious 
    #  4073      4017      3922      3704 
```

```{r topadj}
#when passing colname need to use the standard evaluation versions of the dplyr functions (just append '_' to the function names, ie. group_by_ & summarise_)
top_adj = function(x, y) {
  x %>% 
    group_by_(y) %>%
    count(lemma, sort=T) %>% 
    top_n(10)
}
```


```{r}
all_adj_province <- top_adj(wine_nlp, "province")
```

```{r EDA}
prov = top_province$province
par(mfrow = c(3, 3))
#free scale facet doesn't work with non-cartesian coordinate
#png() and dev.off won't truncate the plot while ggsave could
radial_plot = function(x){
  x %>%
  ggplot(aes(reorder(lemma, -n), n)) + 
  geom_bar(stat="identity", fill="#9fb92d", color="#9fb92d",alpha=0.6, width=1) +
  coord_flip() + 
  theme_minimal() + 
  theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
        plot.title = element_text(face="bold", size=16, hjust = 0.5),
        axis.text.y = element_blank(),
        axis.text.x = element_text(face="bold", size=14,color="#3a5f0b"),
        panel.grid.major = element_blank(),
        legend.position='None',
        text = element_text(family = "Helvetica"),
        plot.background = element_rect(fill = 'ghostwhite',color='white')) +
  labs(title = x,
       subtitle = "") +coord_polar()
}


for (i in prov) {
  png(file=paste0(i,".png"))
  p = radial_plot(all_adj_province %>% 
  filter(province==i))
  print(p)
  dev.off()
}
```


```{r}
all_adj_variety <- top_adj(wine_nlp, "variety")
```


```{r PCA}
library(ggbiplot)
wine_flavor.variety=wine_flavor$variety

wine.pca <- prcomp(wine_flavor[,2:21], scale. = TRUE)
ggbiplot(wine.pca, 
         groups = wine_flavor.variety, labels= wine_flavor.variety
         ) +
  scale_color_discrete() +
  theme(legend.direction = 'horizontal', legend.position = 'None') +
  theme_void()
```

